# 🤖 Dependabot Configuration

version: 2

updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "velyzo"
    assignees:
      - "velyzo"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major updates for stable packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Server dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
    open-pull-requests-limit: 5
    reviewers:
      - "velyzo"
    assignees:
      - "velyzo"
    commit-message:
      prefix: "deps(server)"
      include: "scope"
    labels:
      - "dependencies"
      - "server"
      - "automated"
    ignore:
      # Ignore major updates for critical packages
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlite3"
        update-types: ["version-update:semver-major"]

  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
    open-pull-requests-limit: 5
    reviewers:
      - "velyzo"
    assignees:
      - "velyzo"
    commit-message:
      prefix: "deps(client)"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
      - "automated"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 3
    reviewers:
      - "velyzo"
    assignees:
      - "velyzo"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci"
      - "automated"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
    open-pull-requests-limit: 2
    reviewers:
      - "velyzo"
    assignees:
      - "velyzo"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "infrastructure"
      - "automated"
