name: velink
services:
- name: velink-api
  source_dir: /server
  github:
    repo: Velyzo/velink
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  routes:
  - path: /api
  - path: /
  http_port: 8080
- name: velink-web
  source_dir: /client
  github:
    repo: Velyzo/velink
    branch: main
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  static_sites:
  - name: velink-frontend
    source_dir: /client
    github:
      repo: Velyzo/velink
      branch: main
    build_command: npm ci && npm run build
    output_dir: /build
    index_document: index.html
    error_document: index.html
    routes:
    - path: /
domains:
- domain: velink.app
  type: PRIMARY
