name: Code Quality Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: cd client && npm ci
    
    - name: Run ESLint on server
      run: npx eslint server/ --ext .js,.ts --format=json --output-file=eslint-server.json || true
    
    - name: Run ESLint on client
      run: cd client && npx eslint src/ --ext .js,.jsx,.ts,.tsx --format=json --output-file=../eslint-client.json || true
    
    - name: Run Prettier check
      run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"
    
    - name: Check for security vulnerabilities
      run: |
        npm audit --audit-level=moderate
        cd client && npm audit --audit-level=moderate
    
    - name: TypeScript type checking (client)
      run: cd client && npx tsc --noEmit
    
    - name: Upload ESLint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-results
        path: |
          eslint-server.json
          eslint-client.json
